name: Demo Workflow

on:
  push:
    branches:
      - main   # Runs on push to the main branch

jobs:
  say-hello:
    runs-on: ubuntu-latest   # Use Ubuntu VM

    steps:
      - name: Checkout code
        uses: actions/checkout@v3  # Checkout your repo code
      
      - name: Say Hello
        run: echo "Hello World from GitHub Actions!"

